
logging:
  level:
    org.springframework: info # info || debug || trace
spring:
  datasource:
    url: jdbc:h2:mem:postalitem
    generate-unique-name: false
    name: postalitem
    # driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
